version: '3'
services:
  go-app:
    container_name: "app"
    build:
      context: ./go-app
      dockerfile: Dockerfile
    ports:
      - "1323:1323"  
    depends_on:
      - psql
  psql:
    container_name: "psql"
    build:
      context: ./psql
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: trading
      POSTGRES_USER: nabil
      POSTGRES_PASSWORD: 2000
    ports:
      - "5432:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data  
volumes:
  pgdata: 
